# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Curtis Larson's Blog
tagline:          A lot of software talk.
url:              http://curtismlarson.com/blog
paginate:         1
baseurl:          /blog

disqusid: 3699097

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/quackware/blog

pages_list:
  Archive: 'archive'
  Feed: 'atom.xml'

highlighter: 'pygments'